version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=electronics_components;User=root;Password=your_password;
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=electronics_components
      - MYSQL_ROOT_PASSWORD=your_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 